"""Run the minimal end-to-end Lume pipeline for a task."""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from lume.distill import build_distill_datasets
from lume.execution import ObservedRuntime, OpenAICloudHandler, RuntimeModels
from lume.memory import build_wiki
from lume.routing import route_task


def slugify(text: str) -> str:
    lowered = text.lower()
    lowered = re.sub(r"[^a-z0-9]+", "-", lowered)
    lowered = lowered.strip("-")
    if lowered:
        return lowered
    digest = hashlib.sha1(text.encode("utf-8")).hexdigest()[:8]
    return f"task-{digest}"


def cloud_handler(prompt: str) -> str:
    return (
        "Cloud plan: analyze the task, produce a concise deliverable, "
        "and capture every visible step for shadow logging and later distillation."
    )


def codex_handler(instruction: str) -> str:
    return (
        "Codex output: executed the requested task, persisted the result to a file, "
        "and updated the Lume memory and training pipeline artifacts."
    )


def generate_task_output(task: str) -> str:
    if "爱国散文诗" in task:
        return (
            "《山河与灯火》\n"
            "当清晨越过群山的脊线，第一束光落在江河与城市之间，\n"
            "我看见这片土地不只是名字，而是无数人的肩膀、火焰与明天。\n"
            "黄河的回声、长江的辽阔、边关的月色与街巷的烟火，\n"
            "都在同一种心跳里汇成家园。\n"
            "愿每一个为生活奔跑的人，都能在这片山河里找到自己的光。\n"
        )
    return (
        f"Task: {task}\n\n"
        "This is a minimal Lume pipeline output generated by the Codex runtime wrapper.\n"
        "The main goal is to prove the end-to-end system can route, execute, log, "
        "build wiki memory, and export training datasets.\n"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--task", required=True)
    parser.add_argument(
        "--task-runs-root",
        default=str(ROOT / "data" / "task_runs"),
    )
    parser.add_argument(
        "--wiki-root",
        default=str(ROOT / "data" / "wiki"),
    )
    parser.add_argument(
        "--datasets-root",
        default=str(ROOT / "data" / "datasets"),
    )
    parser.add_argument(
        "--routing-config",
        default=str(ROOT / "configs" / "routing.yaml"),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    task_runs_root = Path(args.task_runs_root)
    openai_cloud = OpenAICloudHandler(model="gpt-5")
    cloud_available = openai_cloud.available
    decision = route_task(
        args.task,
        routing_config_path=Path(args.routing_config),
        task_runs_root=task_runs_root,
        cloud_available=cloud_available,
    )
    task_id = slugify(args.task) + "-pipeline-demo"
    metadata = {
        "pipeline": True,
        "routing_reasons": decision.reasons,
        "cloud_provider": "openai" if cloud_available else "simulated",
        "cloud_simulated": not cloud_available,
    }
    runtime = ObservedRuntime(
        task_id=task_id,
        user_goal=args.task,
        route_mode=decision.mode,
        output_root=task_runs_root,
        models=RuntimeModels(
            primary="gpt-cloud-demo",
            cloud="gpt-cloud-demo",
            codex="codex-demo",
        ),
        cloud_handler=openai_cloud.complete if cloud_available else cloud_handler,
        codex_handler=codex_handler,
        metadata=metadata,
    )

    runtime.user(args.task)
    plan = runtime.cloud.complete(
        f"Create a plan for the task: {args.task}",
        message_type="reasoning",
        metadata={"stage": "planning", "complexity": decision.task_complexity},
    )
    runtime.codex.respond(
        plan,
        message_type="execution",
        metadata={"stage": "execution"},
    )
    runtime.codex.tool(
        "deliver_task_output",
        arguments={"task": args.task},
        output_summary="Generated the user-facing task output.",
        metadata={"stage": "execution"},
    )

    output_text = generate_task_output(args.task)
    output_dir = ROOT / "examples" / "task_samples"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{task_id}.md"
    output_path.write_text(output_text, "utf-8")
    runtime.codex.file(
        str(output_path.relative_to(ROOT)).replace("\\", "/"),
        change_type="created",
        summary="Saved pipeline output for the requested task.",
        metadata={"stage": "execution"},
    )

    task_dir = runtime.finish(
        result_status="completed",
        value_score=0.94,
        notes="Pipeline run completed and output persisted.",
    )

    wiki_paths = build_wiki(task_runs_root, Path(args.wiki_root))
    dataset_paths = build_distill_datasets(
        task_runs_root,
        Path(args.datasets_root),
        ROOT / "data" / "raw_logs",
    )

    print(task_dir)
    print(output_path)
    for path in wiki_paths:
        print(path)
    for path in dataset_paths:
        print(path)


if __name__ == "__main__":
    main()
